apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: comissions.app
  source:
    path: dev/apps
    repoURL: https://github.com/foxutech/kubernetes.git
    targetRevision: HEAD