apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-dev-apps
  namespace: comissions-dev
spec:
  destination:
    namespace: comissions-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL: https://github.com/Data443/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true