apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-api
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Data443/argocd.git
        revision: HEAD
        files:
          - path: "dev/.config/*.json"
  template:
    metadata:
      name: "core-api-{{.deployment.cluster.namespace}}"
    spec:
      project: "{{.deployment.argocd.project}}"
      source:
        repoURL: https://github.com/Data443/argocd.git
        targetRevision: HEAD
        path: charts/core-api
        helm:
          values: |
            fullnameOverride: "core-api"
            image:
              tag: '{{ .apps.core-api.version }}'
            imagePullSecrets:
              - name: comissions-app
            ingress:
              enabled: true
              annotations:
                nginx.ingress.kubernetes.io/proxy-body-size: 100m
                nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
                nginx.ingress.kubernetes.io/proxy-buffering: 'on'
                nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
                nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
              hosts:
                - host: '{{.apps.core-api.ingress.host}}'
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
                - secretName: ''
                  hosts:
                    - '{{.apps.core-api.ingress.host}}'
            resources:
              limits:
                cpu: "500m"
              requests:
                cpu: "10m"

            autoscaling:
              enabled: true
              minReplicas: 1
              maxReplicas: 10
              targetCPUUtilizationPercentage: 80

      destination:
        server: "{{.deployment.cluster.address}}"
        namespace: "{{.deployment.cluster.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
