apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-api
  namespace: comissions-dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: comissions-dev
    server: https://kubernetes.default.svc
  project: comissions.app
  source:
    path: charts/core-api
    repoURL: https://github.com/comissions-app/argocd.git
    targetRevision: HEAD