apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-api
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/comissions-app/argocd.git
      revision: HEAD
      files:
      - path: "dev/.config/config.json"
  template:
    metadata:
      name: 'core-api'
    spec:
      project: 'comissions.app'
      source:
        repoURL: https://github.com/comissions-app/argocd.git
        targetRevision: HEAD
        path: charts/core-api
        helm:
          values: |
            image:
              repository: "{{.apps.core-api.image}}"
              pullPolicy: Always
              tag: "{{.apps.core-api.version}}"

            imagePullSecrets:
              - name: comissions-app
                            
            resources:
              limits:
                cpu: 1
              requests:
                cpu: 100m
            autoscaling:
              enabled: true
              minReplicas: 2
              maxReplicas: 20
              targetCPUUtilizationPercentage: 80
              # targetMemoryUtilizationPercentage: 80

            ingress:
              enabled: true
              annotations:
                nginx.ingress.kubernetes.io/proxy-body-size: 512m
              hosts:
                - host: '{{.apps.core-api.ingress.host}}'
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
                - secretName: 'tls-secret'
                  hosts:
                    - '{{.apps.core-api.ingress.host}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'argo-cd '
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true