apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-api
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/comissions-app/argocd.git
      revision: HEAD
      files:
      - path: "dev/.config/config.json"
  template:
    metadata:
      name: 'core-api'
    spec:
      project: 'comissions.app'
      sources:
        - repoURL: https://github.com/comissions-app/argocd.git
          targetRevision: HEAD
          path: charts/core-api
          helm:
            values: |
              postgres:
                host: "postgres-postgresql"
                port: 5432
                username: "postgres"
                password: "postgres"
                database: "comissionsapp"

                ui:
                  baseUrl: "http://development.comissions.app"

                auth:
                  audience: "https://api.artplatform.com"
                  clientId: "19GWUL7fWFQWEpdFFtlgv2x3kqfSa0ES"
                  clientSecret: "VX5LKeGHeaqKsgNz8Kn1gQ7MSHmwrXJdC2DMjVY82_YHjiRqdPrVNpFFkXBZy8yh"
                  domain: "https://dev-12mb5yq82dow1twh.us.auth0.com/"

                stripe:
                  apiKey: "sk_test_51OdJ1SLooS0IZqYkx2IdNoLcscm6BisgaUyYVIc5jM1RMmarww2e9hLLQS3Atn6TQi00p9YQkCLGQPhAI2gf9ZSY00HmbQYCvP"
                  webhookSecret: "whsec_WTxw2seQHaJjSbLiRr1q8fs1wh8vGdGn"

                novu:
                  apiKey: "287ad99d1cbeba7f96a7d2637b022e6f"

              
              image:
                repository: ghcr.io/comissions-app/core-api
                pullPolicy: Always
                tag: "latest"

              imagePullSecrets:
                - name: comissions-app
                              
              resources:
                limits:
                  cpu: 1
                requests:
                  cpu: 100m
              autoscaling:
                enabled: true
                minReplicas: 2
                maxReplicas: 20
                targetCPUUtilizationPercentage: 80
                # targetMemoryUtilizationPercentage: 80

              ingress:
                enabled: true
                annotations:
                  nginx.ingress.kubernetes.io/proxy-body-size: 512m
                hosts:
                  - host: 'core-api.comissions.dev'
                    paths:
                      - path: /
                        pathType: ImplementationSpecific
                tls:
                  - secretName: 'tls-secret'
                    hosts:
                      - 'core-api.comissions.dev'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
