apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-api
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/comissions-app/argocd.git
      revision: HEAD
      files:
      - path: "dev/.config/config.json"
  template:
    metadata:
      name: 'core-api'
    spec:
      project: 'comissions.app'
      source:
        repoURL: https://github.com/comissions-app/argocd.git
        targetRevision: HEAD
        path: charts/postgres
        helm:
          values: |
            postgresqlHost: "postgres"
            postgresqlPort: 5432
            postgresqlUsername: "postgres"
            postgresqlPassword: "postgres"
            postgresqlDatabase: "comissions"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
